# Generated by Django 3.0.8 on 2020-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
