# Generated by Django 3.0.8 on 2020-09-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200925_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='description',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='quantity',
        ),
    ]
